version: 0.0
os: linux
files:
  - source: mysite.jar
    destination:  /home/ubuntu/myapp/

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    - location: scripts/install.sh
      timeout: 60
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu

